/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sdrerc.ui.menu;

import com.formdev.flatlaf.FlatLightLaf;
import com.sdrerc.ui.views.expedientes.JPanelRegistroExpediente;
import com.sdrerc.ui.views.home.jPanelHome;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author betom
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();  
        initialStyles();
        InitContent();
    }    
    
    private void initialStyles()
    {
        lbl_TituloFormulario.putClientProperty( "FlatLaf.style", "font: 200% $light.font" );
    }
    
        private void InitContent() 
    {
        ShowJPanel(new jPanelHome());
    }
    
    public static void ShowJPanel(JPanel p) 
    {
        p.setSize(1200, 646);
        p.setLocation(0,0);        
        jPanelBody.removeAll();
        jPanelBody.add(p, BorderLayout.CENTER);
        jPanelBody.revalidate();
        jPanelBody.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jpanelMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMenuHome = new javax.swing.JButton();
        btnMenuExpediente = new javax.swing.JButton();
        btnMenuAsignacion = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelHeader = new javax.swing.JPanel();
        lbl_TituloFormulario = new javax.swing.JLabel();
        jPanelBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);

        background.setBackground(new java.awt.Color(255, 204, 204));
        background.setMinimumSize(new java.awt.Dimension(0, 0));
        background.setPreferredSize(new java.awt.Dimension(1180, 640));

        jpanelMenu.setBackground(new java.awt.Color(25, 120, 210));
        jpanelMenu.setPreferredSize(new java.awt.Dimension(270, 640));
        jpanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SDRERC");
        jpanelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 258, -1));

        btnMenuHome.setBackground(new java.awt.Color(25, 120, 210));
        btnMenuHome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuHome.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sdrerc/ui/iconos/icono_home-outline.png"))); // NOI18N
        btnMenuHome.setText("HOME");
        btnMenuHome.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 255, 255)));
        btnMenuHome.setBorderPainted(false);
        btnMenuHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenuHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuHome.setIconTextGap(10);
        btnMenuHome.setInheritsPopupMenu(true);
        btnMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuHomeMouseClicked(evt);
            }
        });
        jpanelMenu.add(btnMenuHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 270, 50));

        btnMenuExpediente.setBackground(new java.awt.Color(25, 120, 210));
        btnMenuExpediente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuExpediente.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuExpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sdrerc/ui/iconos/icono_home-outline.png"))); // NOI18N
        btnMenuExpediente.setText("EXPEDIENTE");
        btnMenuExpediente.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 255, 255)));
        btnMenuExpediente.setBorderPainted(false);
        btnMenuExpediente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenuExpediente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuExpediente.setIconTextGap(10);
        btnMenuExpediente.setInheritsPopupMenu(true);
        btnMenuExpediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuExpedienteMouseClicked(evt);
            }
        });
        jpanelMenu.add(btnMenuExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 270, 50));

        btnMenuAsignacion.setBackground(new java.awt.Color(25, 120, 210));
        btnMenuAsignacion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMenuAsignacion.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuAsignacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sdrerc/ui/iconos/icono_home-outline.png"))); // NOI18N
        btnMenuAsignacion.setText("ASIGNACIÖN");
        btnMenuAsignacion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 255, 255)));
        btnMenuAsignacion.setBorderPainted(false);
        btnMenuAsignacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenuAsignacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuAsignacion.setIconTextGap(10);
        btnMenuAsignacion.setInheritsPopupMenu(true);
        jpanelMenu.add(btnMenuAsignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 270, 50));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jpanelMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 52, 155, 10));

        jPanelHeader.setPreferredSize(new java.awt.Dimension(900, 60));

        lbl_TituloFormulario.setText("HOLA MUNDO");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_TituloFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(583, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_TituloFormulario)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanelBody.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBody.setMaximumSize(null);
        jPanelBody.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addComponent(jpanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE)
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 918, Short.MAX_VALUE))
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
            .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jpanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuExpedienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuExpedienteMouseClicked
        // TODO add your handling code here:
         ShowJPanel(new JPanelRegistroExpediente());
    }//GEN-LAST:event_btnMenuExpedienteMouseClicked

    private void btnMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuHomeMouseClicked
        // TODO add your handling code here:
         ShowJPanel(new jPanelHome());
    }//GEN-LAST:event_btnMenuHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        FlatLightLaf.setup();
        UIManager.put( "Button.arc", 999 );
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel background;
    private javax.swing.JButton btnMenuAsignacion;
    private javax.swing.JButton btnMenuExpediente;
    private javax.swing.JButton btnMenuHome;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpanelMenu;
    private javax.swing.JLabel lbl_TituloFormulario;
    // End of variables declaration//GEN-END:variables
}
