/* ============================================================
   SCRIPT 02 - Seguridad, usuarios, roles y equipos
   Ejecutar conectado como SDRERC_APP.
   ============================================================ */

CREATE TABLE area (
  id_area NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(40) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  descripcion VARCHAR2(500),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE rol (
  id_rol NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(40) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  descripcion VARCHAR2(500),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE usuario (
  id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username VARCHAR2(60) NOT NULL,
  password_hash VARCHAR2(250),
  nombre_completo VARCHAR2(250) NOT NULL,
  tipo_documento VARCHAR2(20),
  numero_documento VARCHAR2(20),
  correo VARCHAR2(250),
  estado VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
  id_legacy NUMBER,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE usuario_rol (
  id_usuario_rol NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_usuario NUMBER NOT NULL,
  id_rol NUMBER NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE equipo (
  id_equipo NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_area NUMBER,
  codigo VARCHAR2(40) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  descripcion VARCHAR2(500),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE equipo_usuario (
  id_equipo_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_equipo NUMBER NOT NULL,
  id_usuario NUMBER NOT NULL,
  es_responsable NUMBER(1) DEFAULT 0 NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE usuario_supervision (
  id_usuario_supervision NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_supervisor NUMBER NOT NULL,
  id_abogado NUMBER NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

