/* ============================================================
   SCRIPT 03 - Entidades externas y canales
   Ejecutar conectado como SDRERC_APP.
   ============================================================ */

CREATE TABLE entidad_externa (
  id_entidad_externa NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(40) NOT NULL,
  nombre VARCHAR2(250) NOT NULL,
  tipo_entidad VARCHAR2(40) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE canal_recepcion (
  id_canal_recepcion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(40) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

