/* ============================================================
   SCRIPT 04 - Catalogos criticos
   Ejecutar conectado como SDRERC_APP.
   ============================================================ */

CREATE TABLE etapa_expediente (
  id_etapa NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(50) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  orden NUMBER(3) NOT NULL,
  visible NUMBER(1) DEFAULT 1 NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE estado_expediente (
  id_estado NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_etapa NUMBER NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  finaliza_expediente NUMBER(1) DEFAULT 0 NOT NULL,
  requiere_comentario NUMBER(1) DEFAULT 0 NOT NULL,
  id_legacy NUMBER,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE tipo_movimiento (
  id_tipo_movimiento NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(80) NOT NULL,
  nombre VARCHAR2(180) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE tipo_documento (
  id_tipo_documento NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(50) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  id_legacy NUMBER,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE tipo_acta (
  id_tipo_acta NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(50) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  id_legacy NUMBER,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE procedimiento_registral (
  id_procedimiento_registral NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(180) NOT NULL,
  id_legacy NUMBER,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE tipo_documento_adjunto (
  id_tipo_documento_adjunto NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(180) NOT NULL,
  id_legacy NUMBER,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE estado_documento (
  id_estado_documento NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE tipo_observacion (
  id_tipo_observacion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  id_legacy NUMBER,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE tipo_resultado_evaluacion (
  id_tipo_resultado_evaluacion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  id_legacy NUMBER,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE tipo_resultado_ejecucion (
  id_tipo_resultado_ejecucion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  id_legacy NUMBER,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE tipo_notificacion (
  id_tipo_notificacion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE estado_notificacion (
  id_estado_notificacion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE estado_cargo_acuse (
  id_estado_cargo_acuse NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE tipo_resolucion (
  id_tipo_resolucion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE motivo_no_corresponde (
  id_motivo_no_corresponde NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(200) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE motivo_archivo (
  id_motivo_archivo NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(200) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE motivo_correccion (
  id_motivo_correccion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(60) NOT NULL,
  nombre VARCHAR2(200) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

