/* ============================================================
   SCRIPT 05 - Flujo, etapas, estados y transiciones
   Ejecutar conectado como SDRERC_APP.
   ============================================================ */

CREATE TABLE flujo (
  id_flujo NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(50) NOT NULL,
  nombre VARCHAR2(150) NOT NULL,
  version_flujo VARCHAR2(30) DEFAULT '1.0' NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE flujo_transicion (
  id_flujo_transicion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_flujo NUMBER NOT NULL,
  id_etapa_origen NUMBER,
  id_estado_origen NUMBER,
  id_etapa_destino NUMBER NOT NULL,
  id_estado_destino NUMBER NOT NULL,
  codigo_accion VARCHAR2(80) NOT NULL,
  nombre_accion VARCHAR2(180) NOT NULL,
  requiere_comentario NUMBER(1) DEFAULT 0 NOT NULL,
  requiere_documento NUMBER(1) DEFAULT 0 NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

