/* ============================================================
   SCRIPT 06 - Tablas transaccionales MVP
   Ejecutar conectado como SDRERC_APP.
   ============================================================ */

CREATE TABLE persona (
  id_persona NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tipo_documento VARCHAR2(20),
  numero_documento VARCHAR2(30),
  nombres VARCHAR2(200),
  apellidos VARCHAR2(250),
  razon_social VARCHAR2(300),
  correo_electronico VARCHAR2(250),
  telefono VARCHAR2(30),
  direccion VARCHAR2(500),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente (
  id_expediente NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  numero_expediente VARCHAR2(100),
  numero_tramite_documentario VARCHAR2(50),
  id_etapa_actual NUMBER NOT NULL,
  id_estado_actual NUMBER NOT NULL,
  id_usuario_responsable_actual NUMBER,
  id_usuario_abogado_inicial NUMBER,
  id_equipo_responsable_actual NUMBER,
  fecha_registro TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  fecha_ultimo_movimiento TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  fecha_vencimiento DATE,
  prioridad VARCHAR2(20),
  requiere_publicacion NUMBER(1) DEFAULT 0 NOT NULL,
  expediente_digital_completo NUMBER(1) DEFAULT 0 NOT NULL,
  archivado NUMBER(1) DEFAULT 0 NOT NULL,
  cerrado NUMBER(1) DEFAULT 0 NOT NULL,
  id_legacy NUMBER,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_solicitud (
  id_expediente_solicitud NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_entidad_origen NUMBER,
  id_canal_recepcion NUMBER,
  id_persona_solicitante NUMBER,
  numero_tramite_documentario VARCHAR2(50),
  fecha_recepcion DATE,
  asunto VARCHAR2(500),
  observacion VARCHAR2(1000),
  es_tramite_virtual NUMBER(1) DEFAULT 0 NOT NULL,
  correo_electronico VARCHAR2(250),
  potencial_duplicado NUMBER(1) DEFAULT 0 NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_persona (
  id_expediente_persona NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_persona NUMBER NOT NULL,
  tipo_relacion_persona VARCHAR2(40) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_acta (
  id_expediente_acta NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_tipo_acta NUMBER,
  numero_acta VARCHAR2(50),
  anio_acta NUMBER(4),
  oficina_registral VARCHAR2(250),
  libro VARCHAR2(80),
  folio VARCHAR2(80),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_relacion (
  id_expediente_relacion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente_principal NUMBER NOT NULL,
  id_expediente_relacionado NUMBER,
  tipo_relacion VARCHAR2(60) NOT NULL,
  descripcion VARCHAR2(1000),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_asignacion (
  id_expediente_asignacion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_usuario_asignado NUMBER NOT NULL,
  id_equipo_asignado NUMBER,
  id_etapa NUMBER NOT NULL,
  fecha_asignacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  fecha_recepcion TIMESTAMP,
  activa NUMBER(1) DEFAULT 1 NOT NULL,
  es_abogado_principal NUMBER(1) DEFAULT 0 NOT NULL,
  es_reasignacion_excepcional NUMBER(1) DEFAULT 0 NOT NULL,
  motivo VARCHAR2(1000),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_documento (
  id_expediente_documento NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_tipo_documento_adjunto NUMBER,
  id_estado_documento NUMBER,
  nombre_documento VARCHAR2(300) NOT NULL,
  numero_documento VARCHAR2(100),
  ruta_archivo VARCHAR2(1000),
  hash_archivo VARCHAR2(128),
  fecha_documento DATE,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_documento_analizado (
  id_documento_analizado NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_tipo_documento_adjunto NUMBER,
  id_estado_documento NUMBER,
  fecha_documento DATE,
  descripcion VARCHAR2(1000),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_evaluacion (
  id_expediente_evaluacion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_tipo_resultado_evaluacion NUMBER,
  corresponde NUMBER(1),
  id_motivo_no_corresponde NUMBER,
  incorporado NUMBER(1) NOT NULL,
  requiere_reconstitucion NUMBER(1) DEFAULT 0 NOT NULL,
  tiene_legitimidad NUMBER(1) DEFAULT 0 NOT NULL,
  cumple_medios_probatorios NUMBER(1) DEFAULT 0 NOT NULL,
  fundamento VARCHAR2(2000),
  fecha_evaluacion TIMESTAMP,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_observacion (
  id_expediente_observacion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_tipo_observacion NUMBER,
  id_motivo_correccion NUMBER,
  origen_observacion VARCHAR2(40) NOT NULL,
  descripcion VARCHAR2(1500),
  subsanada NUMBER(1) DEFAULT 0 NOT NULL,
  fecha_observacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_resolucion (
  id_expediente_resolucion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_tipo_resolucion NUMBER,
  numero_resolucion VARCHAR2(100),
  fecha_resolucion DATE,
  fecha_firma TIMESTAMP,
  id_documento_resolucion NUMBER,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_notificacion (
  id_expediente_notificacion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_expediente_resolucion NUMBER,
  id_tipo_notificacion NUMBER NOT NULL,
  id_estado_notificacion NUMBER NOT NULL,
  numero_intento NUMBER(2) NOT NULL,
  fecha_programada DATE,
  fecha_envio TIMESTAMP,
  resultado VARCHAR2(150),
  requiere_publicacion NUMBER(1) DEFAULT 0 NOT NULL,
  observacion VARCHAR2(1000),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_cargo_acuse (
  id_expediente_cargo_acuse NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_expediente_notificacion NUMBER NOT NULL,
  id_estado_cargo_acuse NUMBER NOT NULL,
  fecha_recepcion TIMESTAMP,
  recibido_por VARCHAR2(250),
  id_documento_cargo NUMBER,
  observacion VARCHAR2(1000),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_digital (
  id_expediente_digital NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  codigo_expediente_digital VARCHAR2(100),
  ruta_carpeta VARCHAR2(1000),
  enlace_carpeta VARCHAR2(1000),
  documentos_cargados NUMBER(1) DEFAULT 0 NOT NULL,
  completo NUMBER(1) DEFAULT 0 NOT NULL,
  id_usuario_responsable NUMBER,
  id_usuario_custodio NUMBER,
  fecha_creacion_carpeta TIMESTAMP,
  fecha_actualizacion TIMESTAMP,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_historial (
  id_expediente_historial NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_tipo_movimiento NUMBER NOT NULL,
  fecha_movimiento TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  id_etapa_origen NUMBER,
  id_estado_origen NUMBER,
  id_etapa_destino NUMBER,
  id_estado_destino NUMBER,
  id_usuario_origen NUMBER,
  id_usuario_destino NUMBER,
  id_equipo_origen NUMBER,
  id_equipo_destino NUMBER,
  id_entidad_externa_origen NUMBER,
  id_entidad_externa_destino NUMBER,
  tabla_relacionada VARCHAR2(80),
  id_registro_relacionado NUMBER,
  comentario VARCHAR2(2000),
  motivo VARCHAR2(1000),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE auditoria_evento (
  id_auditoria_evento NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tabla_afectada VARCHAR2(80) NOT NULL,
  id_registro VARCHAR2(80) NOT NULL,
  operacion VARCHAR2(20) NOT NULL,
  id_usuario NUMBER,
  fecha_evento TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modulo VARCHAR2(80),
  origen_accion VARCHAR2(120),
  equipo_cliente VARCHAR2(120),
  valor_anterior CLOB,
  valor_nuevo CLOB
);

CREATE TABLE legacy_estado_map (
  id_legacy_estado_map NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_legacy NUMBER NOT NULL,
  descripcion_legacy VARCHAR2(150) NOT NULL,
  codigo_estado_nuevo VARCHAR2(60) NOT NULL,
  codigo_etapa_nueva VARCHAR2(50) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE legacy_catalogo_map (
  id_legacy_catalogo_map NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tabla_catalogo_nueva VARCHAR2(80) NOT NULL,
  id_legacy_catalogo NUMBER,
  id_legacy_item NUMBER,
  descripcion_legacy VARCHAR2(250),
  codigo_nuevo VARCHAR2(80),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

