/* ============================================================
   SCRIPT 07 - Tablas Fase 2
   Ejecutar conectado como SDRERC_APP cuando se habilite la fase.
   ============================================================ */

CREATE TABLE expediente_derivacion_externa (
  id_derivacion_externa NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_entidad_destino NUMBER NOT NULL,
  tipo_derivacion VARCHAR2(60) NOT NULL,
  numero_oficio VARCHAR2(100),
  fecha_envio DATE,
  fecha_respuesta DATE,
  estado_respuesta VARCHAR2(60),
  id_documento_enviado NUMBER,
  id_documento_respuesta NUMBER,
  comentario VARCHAR2(1500),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_publicacion (
  id_expediente_publicacion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_expediente_notificacion NUMBER,
  tipo_publicacion VARCHAR2(60),
  estado_publicacion VARCHAR2(60) NOT NULL,
  fecha_generacion DATE,
  fecha_publicacion DATE,
  medio_publicacion VARCHAR2(250),
  numero_publicacion VARCHAR2(100),
  observacion VARCHAR2(1500),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE plazo_configuracion (
  id_plazo_configuracion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_etapa NUMBER,
  id_tipo_documento NUMBER,
  dias_plazo NUMBER(4) NOT NULL,
  porcentaje_verde_desde NUMBER(3) DEFAULT 51 NOT NULL,
  porcentaje_amarillo_desde NUMBER(3) DEFAULT 21 NOT NULL,
  porcentaje_rojo_desde NUMBER(3) DEFAULT 0 NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_plazo (
  id_expediente_plazo NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_plazo_configuracion NUMBER,
  fecha_inicio DATE NOT NULL,
  fecha_vencimiento DATE NOT NULL,
  estado_plazo VARCHAR2(30) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_alerta (
  id_expediente_alerta NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  tipo_alerta VARCHAR2(60) NOT NULL,
  mensaje VARCHAR2(500) NOT NULL,
  nivel VARCHAR2(20) NOT NULL,
  atendida NUMBER(1) DEFAULT 0 NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE permiso (
  id_permiso NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  codigo VARCHAR2(80) NOT NULL,
  nombre VARCHAR2(180) NOT NULL,
  modulo VARCHAR2(80) NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE rol_permiso (
  id_rol_permiso NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_rol NUMBER NOT NULL,
  id_permiso NUMBER NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE flujo_transicion_rol (
  id_flujo_transicion_rol NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_flujo_transicion NUMBER NOT NULL,
  id_rol NUMBER NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE flujo_transicion_equipo (
  id_flujo_transicion_equipo NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_flujo_transicion NUMBER NOT NULL,
  id_equipo NUMBER NOT NULL,
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

CREATE TABLE expediente_metrica_etapa (
  id_expediente_metrica_etapa NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_expediente NUMBER NOT NULL,
  id_etapa NUMBER NOT NULL,
  fecha_entrada TIMESTAMP NOT NULL,
  fecha_salida TIMESTAMP,
  horas_permanencia NUMBER(12,2),
  activo NUMBER(1) DEFAULT 1 NOT NULL,
  creado_por NUMBER,
  creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  modificado_por NUMBER,
  modificado_en TIMESTAMP
);

