/* ============================================================
   SCRIPT 24 - Feriados y plazos habiles
   Ejecutar conectado como SDRERC_APP cuando se habilite la mejora.
   Script idempotente, no destructivo y sin datos transaccionales.
   ============================================================ */

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM user_tables
   WHERE table_name = 'FERIADO_NACIONAL';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE feriado_nacional (
        id_feriado NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        fecha DATE NOT NULL,
        nombre VARCHAR2(150) NOT NULL,
        tipo VARCHAR2(50) DEFAULT ''NACIONAL'' NOT NULL,
        activo NUMBER(1) DEFAULT 1 NOT NULL,
        observacion VARCHAR2(300),
        usuario_creacion VARCHAR2(80),
        fecha_creacion DATE DEFAULT SYSDATE NOT NULL,
        usuario_modificacion VARCHAR2(80),
        fecha_modificacion DATE,
        creado_por NUMBER,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        modificado_por NUMBER,
        modificado_en TIMESTAMP
      )';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_FERIADO_NACIONAL';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE feriado_nacional ADD CONSTRAINT pk_feriado_nacional PRIMARY KEY (id_feriado)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'UK_FERIADO_NACIONAL_FECHA_TIPO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE feriado_nacional ADD CONSTRAINT uk_feriado_nacional_fecha_tipo UNIQUE (fecha, tipo)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'CK_FERIADO_NACIONAL_ACTIVO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE feriado_nacional ADD CONSTRAINT ck_feriado_nacional_activo CHECK (activo IN (0, 1))';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_FERIADO_NACIONAL_FECHA';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_feriado_nacional_fecha ON feriado_nacional (fecha, activo)';
  END IF;
END;
/

DECLARE
  v_table_count NUMBER;
  v_column_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_table_count FROM user_tables WHERE table_name = 'PLAZO_CONFIGURACION';

  IF v_table_count > 0 THEN
    SELECT COUNT(*)
      INTO v_column_count
      FROM user_tab_cols
     WHERE table_name = 'PLAZO_CONFIGURACION'
       AND column_name = 'UNIDAD_PLAZO';

    IF v_column_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE plazo_configuracion ADD unidad_plazo VARCHAR2(20) DEFAULT ''HABILES'' NOT NULL';
    END IF;
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'CK_PLAZO_CONFIG_UNIDAD';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE plazo_configuracion ADD CONSTRAINT ck_plazo_config_unidad CHECK (unidad_plazo IN (''HABILES'', ''CALENDARIO''))';
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

SELECT table_name
  FROM user_tables
 WHERE table_name IN ('FERIADO_NACIONAL', 'PLAZO_CONFIGURACION')
 ORDER BY table_name;
