/* ============================================================
   SCRIPT 34 - Ubigeo para notificacion y ubicacion en Registro Manual
   Ejecutar conectado como SDRERC_APP.
   Script idempotente, no destructivo y sin datos transaccionales.

   Nota:
   - Crea catalogos V2 de departamento/provincia/distrito.
   - Agrega columnas nullable a PERSONA para conservar ubicacion del solicitante.
   - Carga departamentos nacionales y una base inicial de Lima/Callao para pruebas.
   - Ampliar provincias/distritos con el maestro institucional oficial cuando se valide.
   ============================================================ */

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'UBIGEO_DEPARTAMENTO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE ubigeo_departamento (
        id_ubigeo_departamento NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        codigo VARCHAR2(2) NOT NULL,
        nombre VARCHAR2(120) NOT NULL,
        activo NUMBER(1) DEFAULT 1 NOT NULL,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        modificado_en TIMESTAMP
      )';
  END IF;
END;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'UBIGEO_PROVINCIA';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE ubigeo_provincia (
        id_ubigeo_provincia NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_ubigeo_departamento NUMBER NOT NULL,
        codigo VARCHAR2(4) NOT NULL,
        nombre VARCHAR2(120) NOT NULL,
        activo NUMBER(1) DEFAULT 1 NOT NULL,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        modificado_en TIMESTAMP
      )';
  END IF;
END;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'UBIGEO_DISTRITO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE ubigeo_distrito (
        id_ubigeo_distrito NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_ubigeo_provincia NUMBER NOT NULL,
        codigo VARCHAR2(6) NOT NULL,
        nombre VARCHAR2(120) NOT NULL,
        activo NUMBER(1) DEFAULT 1 NOT NULL,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        modificado_en TIMESTAMP
      )';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_UBIGEO_DEPARTAMENTO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_departamento ADD CONSTRAINT pk_ubigeo_departamento PRIMARY KEY (id_ubigeo_departamento)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_UBIGEO_PROVINCIA';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_provincia ADD CONSTRAINT pk_ubigeo_provincia PRIMARY KEY (id_ubigeo_provincia)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_UBIGEO_DISTRITO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_distrito ADD CONSTRAINT pk_ubigeo_distrito PRIMARY KEY (id_ubigeo_distrito)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'UK_UBIGEO_DEP_COD';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_departamento ADD CONSTRAINT uk_ubigeo_dep_cod UNIQUE (codigo)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'UK_UBIGEO_PROV_COD';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_provincia ADD CONSTRAINT uk_ubigeo_prov_cod UNIQUE (codigo)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'UK_UBIGEO_DIST_COD';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_distrito ADD CONSTRAINT uk_ubigeo_dist_cod UNIQUE (codigo)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_UBIGEO_PROV_DEP';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_provincia ADD CONSTRAINT fk_ubigeo_prov_dep FOREIGN KEY (id_ubigeo_departamento) REFERENCES ubigeo_departamento (id_ubigeo_departamento)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_UBIGEO_DIST_PROV';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_distrito ADD CONSTRAINT fk_ubigeo_dist_prov FOREIGN KEY (id_ubigeo_provincia) REFERENCES ubigeo_provincia (id_ubigeo_provincia)';
  END IF;
END;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name = 'PERSONA' AND column_name = 'ID_UBIGEO_DISTRITO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE persona ADD id_ubigeo_distrito NUMBER';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name = 'PERSONA' AND column_name = 'DEPARTAMENTO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE persona ADD departamento VARCHAR2(120)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name = 'PERSONA' AND column_name = 'PROVINCIA';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE persona ADD provincia VARCHAR2(120)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name = 'PERSONA' AND column_name = 'DISTRITO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE persona ADD distrito VARCHAR2(120)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_PERSONA_UBIGEO_DISTRITO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE persona ADD CONSTRAINT fk_persona_ubigeo_distrito FOREIGN KEY (id_ubigeo_distrito) REFERENCES ubigeo_distrito (id_ubigeo_distrito)';
  END IF;
END;



SELECT table_name
  FROM user_tables
 WHERE table_name IN ('UBIGEO_DEPARTAMENTO', 'UBIGEO_PROVINCIA', 'UBIGEO_DISTRITO')
 ORDER BY table_name;
