/* ============================================================
   SCRIPT 34 - Ubigeo para notificacion y ubicacion en Registro Manual
   Ejecutar conectado como SDRERC_APP.
   Script idempotente, no destructivo y sin datos transaccionales.

   Nota:
   - Crea catalogos V2 de departamento/provincia/distrito.
   - Agrega columnas nullable a PERSONA para conservar ubicacion del solicitante.
   - Carga departamentos nacionales y una base inicial de Lima/Callao para pruebas.
   - Ampliar provincias/distritos con el maestro institucional oficial cuando se valide.
   ============================================================ */

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'UBIGEO_DEPARTAMENTO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE ubigeo_departamento (
        id_ubigeo_departamento NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        codigo VARCHAR2(2) NOT NULL,
        nombre VARCHAR2(120) NOT NULL,
        activo NUMBER(1) DEFAULT 1 NOT NULL,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        modificado_en TIMESTAMP
      )';
  END IF;
END;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'UBIGEO_PROVINCIA';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE ubigeo_provincia (
        id_ubigeo_provincia NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_ubigeo_departamento NUMBER NOT NULL,
        codigo VARCHAR2(4) NOT NULL,
        nombre VARCHAR2(120) NOT NULL,
        activo NUMBER(1) DEFAULT 1 NOT NULL,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        modificado_en TIMESTAMP
      )';
  END IF;
END;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'UBIGEO_DISTRITO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE ubigeo_distrito (
        id_ubigeo_distrito NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_ubigeo_provincia NUMBER NOT NULL,
        codigo VARCHAR2(6) NOT NULL,
        nombre VARCHAR2(120) NOT NULL,
        activo NUMBER(1) DEFAULT 1 NOT NULL,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        modificado_en TIMESTAMP
      )';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_UBIGEO_DEPARTAMENTO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_departamento ADD CONSTRAINT pk_ubigeo_departamento PRIMARY KEY (id_ubigeo_departamento)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_UBIGEO_PROVINCIA';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_provincia ADD CONSTRAINT pk_ubigeo_provincia PRIMARY KEY (id_ubigeo_provincia)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'PK_UBIGEO_DISTRITO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_distrito ADD CONSTRAINT pk_ubigeo_distrito PRIMARY KEY (id_ubigeo_distrito)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'UK_UBIGEO_DEP_COD';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_departamento ADD CONSTRAINT uk_ubigeo_dep_cod UNIQUE (codigo)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'UK_UBIGEO_PROV_COD';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_provincia ADD CONSTRAINT uk_ubigeo_prov_cod UNIQUE (codigo)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'UK_UBIGEO_DIST_COD';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_distrito ADD CONSTRAINT uk_ubigeo_dist_cod UNIQUE (codigo)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_UBIGEO_PROV_DEP';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_provincia ADD CONSTRAINT fk_ubigeo_prov_dep FOREIGN KEY (id_ubigeo_departamento) REFERENCES ubigeo_departamento (id_ubigeo_departamento)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_UBIGEO_DIST_PROV';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ubigeo_distrito ADD CONSTRAINT fk_ubigeo_dist_prov FOREIGN KEY (id_ubigeo_provincia) REFERENCES ubigeo_provincia (id_ubigeo_provincia)';
  END IF;
END;

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name = 'PERSONA' AND column_name = 'ID_UBIGEO_DISTRITO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE persona ADD id_ubigeo_distrito NUMBER';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name = 'PERSONA' AND column_name = 'DEPARTAMENTO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE persona ADD departamento VARCHAR2(120)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name = 'PERSONA' AND column_name = 'PROVINCIA';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE persona ADD provincia VARCHAR2(120)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_tab_columns WHERE table_name = 'PERSONA' AND column_name = 'DISTRITO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE persona ADD distrito VARCHAR2(120)';
  END IF;
END;

DECLARE v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_constraints WHERE constraint_name = 'FK_PERSONA_UBIGEO_DISTRITO';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE persona ADD CONSTRAINT fk_persona_ubigeo_distrito FOREIGN KEY (id_ubigeo_distrito) REFERENCES ubigeo_distrito (id_ubigeo_distrito)';
  END IF;
END;

MERGE INTO ubigeo_departamento d USING (
  SELECT '01' codigo, 'Amazonas' nombre FROM dual UNION ALL
  SELECT '02', 'Áncash' FROM dual UNION ALL
  SELECT '03', 'Apurímac' FROM dual UNION ALL
  SELECT '04', 'Arequipa' FROM dual UNION ALL
  SELECT '05', 'Ayacucho' FROM dual UNION ALL
  SELECT '06', 'Cajamarca' FROM dual UNION ALL
  SELECT '07', 'Callao' FROM dual UNION ALL
  SELECT '08', 'Cusco' FROM dual UNION ALL
  SELECT '09', 'Huancavelica' FROM dual UNION ALL
  SELECT '10', 'Huánuco' FROM dual UNION ALL
  SELECT '11', 'Ica' FROM dual UNION ALL
  SELECT '12', 'Junín' FROM dual UNION ALL
  SELECT '13', 'La Libertad' FROM dual UNION ALL
  SELECT '14', 'Lambayeque' FROM dual UNION ALL
  SELECT '15', 'Lima' FROM dual UNION ALL
  SELECT '16', 'Loreto' FROM dual UNION ALL
  SELECT '17', 'Madre de Dios' FROM dual UNION ALL
  SELECT '18', 'Moquegua' FROM dual UNION ALL
  SELECT '19', 'Pasco' FROM dual UNION ALL
  SELECT '20', 'Piura' FROM dual UNION ALL
  SELECT '21', 'Puno' FROM dual UNION ALL
  SELECT '22', 'San Martín' FROM dual UNION ALL
  SELECT '23', 'Tacna' FROM dual UNION ALL
  SELECT '24', 'Tumbes' FROM dual UNION ALL
  SELECT '25', 'Ucayali' FROM dual
) s ON (d.codigo = s.codigo)
WHEN MATCHED THEN UPDATE SET d.nombre = s.nombre, d.activo = 1, d.modificado_en = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (codigo, nombre, activo) VALUES (s.codigo, s.nombre, 1);

MERGE INTO ubigeo_provincia p USING (
  SELECT '1501' codigo, 'Lima' nombre, '15' cod_dep FROM dual UNION ALL
  SELECT '0701' codigo, 'Callao' nombre, '07' cod_dep FROM dual
) s ON (p.codigo = s.codigo)
WHEN MATCHED THEN UPDATE SET p.nombre = s.nombre, p.activo = 1, p.modificado_en = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (id_ubigeo_departamento, codigo, nombre, activo)
  VALUES ((SELECT id_ubigeo_departamento FROM ubigeo_departamento WHERE codigo = s.cod_dep), s.codigo, s.nombre, 1);

MERGE INTO ubigeo_distrito x USING (
  SELECT '150101' codigo, 'Lima' nombre, '1501' cod_prov FROM dual UNION ALL
  SELECT '150102', 'Ancón', '1501' FROM dual UNION ALL
  SELECT '150103', 'Ate', '1501' FROM dual UNION ALL
  SELECT '150104', 'Barranco', '1501' FROM dual UNION ALL
  SELECT '150105', 'Breña', '1501' FROM dual UNION ALL
  SELECT '150106', 'Carabayllo', '1501' FROM dual UNION ALL
  SELECT '150107', 'Chaclacayo', '1501' FROM dual UNION ALL
  SELECT '150108', 'Chorrillos', '1501' FROM dual UNION ALL
  SELECT '150109', 'Cieneguilla', '1501' FROM dual UNION ALL
  SELECT '150110', 'Comas', '1501' FROM dual UNION ALL
  SELECT '150111', 'El Agustino', '1501' FROM dual UNION ALL
  SELECT '150112', 'Independencia', '1501' FROM dual UNION ALL
  SELECT '150113', 'Jesús María', '1501' FROM dual UNION ALL
  SELECT '150114', 'La Molina', '1501' FROM dual UNION ALL
  SELECT '150115', 'La Victoria', '1501' FROM dual UNION ALL
  SELECT '150116', 'Lince', '1501' FROM dual UNION ALL
  SELECT '150117', 'Los Olivos', '1501' FROM dual UNION ALL
  SELECT '150118', 'Lurigancho', '1501' FROM dual UNION ALL
  SELECT '150119', 'Lurín', '1501' FROM dual UNION ALL
  SELECT '150120', 'Magdalena del Mar', '1501' FROM dual UNION ALL
  SELECT '150121', 'Pueblo Libre', '1501' FROM dual UNION ALL
  SELECT '150122', 'Miraflores', '1501' FROM dual UNION ALL
  SELECT '150123', 'Pachacámac', '1501' FROM dual UNION ALL
  SELECT '150124', 'Pucusana', '1501' FROM dual UNION ALL
  SELECT '150125', 'Puente Piedra', '1501' FROM dual UNION ALL
  SELECT '150126', 'Punta Hermosa', '1501' FROM dual UNION ALL
  SELECT '150127', 'Punta Negra', '1501' FROM dual UNION ALL
  SELECT '150128', 'Rímac', '1501' FROM dual UNION ALL
  SELECT '150129', 'San Bartolo', '1501' FROM dual UNION ALL
  SELECT '150130', 'San Borja', '1501' FROM dual UNION ALL
  SELECT '150131', 'San Isidro', '1501' FROM dual UNION ALL
  SELECT '150132', 'San Juan de Lurigancho', '1501' FROM dual UNION ALL
  SELECT '150133', 'San Juan de Miraflores', '1501' FROM dual UNION ALL
  SELECT '150134', 'San Luis', '1501' FROM dual UNION ALL
  SELECT '150135', 'San Martín de Porres', '1501' FROM dual UNION ALL
  SELECT '150136', 'San Miguel', '1501' FROM dual UNION ALL
  SELECT '150137', 'Santa Anita', '1501' FROM dual UNION ALL
  SELECT '150138', 'Santa María del Mar', '1501' FROM dual UNION ALL
  SELECT '150139', 'Santa Rosa', '1501' FROM dual UNION ALL
  SELECT '150140', 'Santiago de Surco', '1501' FROM dual UNION ALL
  SELECT '150141', 'Surquillo', '1501' FROM dual UNION ALL
  SELECT '150142', 'Villa El Salvador', '1501' FROM dual UNION ALL
  SELECT '150143', 'Villa María del Triunfo', '1501' FROM dual UNION ALL
  SELECT '070101', 'Callao', '0701' FROM dual UNION ALL
  SELECT '070102', 'Bellavista', '0701' FROM dual UNION ALL
  SELECT '070103', 'Carmen de la Legua Reynoso', '0701' FROM dual UNION ALL
  SELECT '070104', 'La Perla', '0701' FROM dual UNION ALL
  SELECT '070105', 'La Punta', '0701' FROM dual UNION ALL
  SELECT '070106', 'Ventanilla', '0701' FROM dual UNION ALL
  SELECT '070107', 'Mi Perú', '0701' FROM dual
) s ON (x.codigo = s.codigo)
WHEN MATCHED THEN UPDATE SET x.nombre = s.nombre, x.activo = 1, x.modificado_en = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (id_ubigeo_provincia, codigo, nombre, activo)
  VALUES ((SELECT id_ubigeo_provincia FROM ubigeo_provincia WHERE codigo = s.cod_prov), s.codigo, s.nombre, 1);

SELECT table_name
  FROM user_tables
 WHERE table_name IN ('UBIGEO_DEPARTAMENTO', 'UBIGEO_PROVINCIA', 'UBIGEO_DISTRITO')
 ORDER BY table_name;
