/* ============================================================
   SCRIPT 38 - Analisis multiple por expediente
   Crea soporte relacional para agrupar documentos y resultado
   por cada bloque de analisis.

   IMPORTANTE:
   - Script idempotente.
   - No ejecutar automaticamente desde la aplicacion.
   - No recalcula ni modifica expedientes historicos.
   ============================================================ */

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1)
    INTO v_count
    FROM user_tables
   WHERE table_name = 'EXPEDIENTE_ANALISIS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE expediente_analisis (
        id_expediente_analisis NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_expediente NUMBER NOT NULL,
        numero_analisis NUMBER NOT NULL,
        titulo VARCHAR2(120),
        estado_analisis VARCHAR2(40) DEFAULT ''EN_PROCESO'' NOT NULL,
        activo NUMBER(1) DEFAULT 1 NOT NULL,
        creado_por NUMBER,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        modificado_por NUMBER,
        modificado_en TIMESTAMP
      )';

    EXECUTE IMMEDIATE 'ALTER TABLE expediente_analisis ADD CONSTRAINT pk_expediente_analisis PRIMARY KEY (id_expediente_analisis)';
    EXECUTE IMMEDIATE 'ALTER TABLE expediente_analisis ADD CONSTRAINT fk_exp_analisis_expediente FOREIGN KEY (id_expediente) REFERENCES expediente(id_expediente)';
    EXECUTE IMMEDIATE 'ALTER TABLE expediente_analisis ADD CONSTRAINT ck_exp_analisis_activo CHECK (activo IN (0,1))';
    EXECUTE IMMEDIATE 'ALTER TABLE expediente_analisis ADD CONSTRAINT uq_exp_analisis_numero UNIQUE (id_expediente, numero_analisis)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1)
    INTO v_count
    FROM user_tab_columns
   WHERE table_name = 'EXPEDIENTE_DOCUMENTO_ANALIZADO'
     AND column_name = 'ID_EXPEDIENTE_ANALISIS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE expediente_documento_analizado ADD id_expediente_analisis NUMBER';
    EXECUTE IMMEDIATE 'ALTER TABLE expediente_documento_analizado ADD CONSTRAINT fk_doc_analizado_analisis FOREIGN KEY (id_expediente_analisis) REFERENCES expediente_analisis(id_expediente_analisis)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1)
    INTO v_count
    FROM user_tab_columns
   WHERE table_name = 'EXPEDIENTE_EVALUACION'
     AND column_name = 'ID_EXPEDIENTE_ANALISIS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE expediente_evaluacion ADD id_expediente_analisis NUMBER';
    EXECUTE IMMEDIATE 'ALTER TABLE expediente_evaluacion ADD CONSTRAINT fk_eval_analisis FOREIGN KEY (id_expediente_analisis) REFERENCES expediente_analisis(id_expediente_analisis)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1)
    INTO v_count
    FROM user_indexes
   WHERE index_name = 'IX_EXP_ANALISIS_EXPEDIENTE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_exp_analisis_expediente ON expediente_analisis(id_expediente, activo, numero_analisis)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1)
    INTO v_count
    FROM user_indexes
   WHERE index_name = 'IX_DOC_ANALIZADO_ANALISIS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_doc_analizado_analisis ON expediente_documento_analizado(id_expediente_analisis, activo)';
  END IF;
END;
/

