/* ============================================================
   SCRIPT 47 - Limpieza de datos de prueba de expedientes/personas
   Ejecutar conectado como SDRERC_APP desde DBeaver.

   Alcance:
   - Elimina expedientes, solicitudes, documentos, relaciones,
     historial, alertas, metricas, notificaciones, publicacion
     y personas transaccionales para reiniciar pruebas.
   - No elimina catalogos, usuarios, roles, equipos, plazos,
     ubigeo ni configuracion maestra.
   - No usa DROP/TRUNCATE.
   - Reinicia identities cuando Oracle lo soporta.

   ADVERTENCIA:
   Este script borra datos transaccionales. Usarlo solo en ambiente
   de pruebas o con backup validado.
   ============================================================ */

--SET SERVEROUTPUT ON;

DECLARE
  PROCEDURE delete_if_exists(p_table_name IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(1)
      INTO v_count
      FROM user_tables
     WHERE table_name = UPPER(p_table_name);

    IF v_count > 0 THEN
      EXECUTE IMMEDIATE 'DELETE FROM ' || p_table_name;
      DBMS_OUTPUT.PUT_LINE('OK DELETE ' || p_table_name);
    ELSE
      DBMS_OUTPUT.PUT_LINE('NO EXISTE ' || p_table_name);
    END IF;
  END;

  PROCEDURE reset_identity_if_exists(
    p_table_name  IN VARCHAR2,
    p_column_name IN VARCHAR2
  ) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(1)
      INTO v_count
      FROM user_tab_identity_cols
     WHERE table_name = UPPER(p_table_name)
       AND column_name = UPPER(p_column_name);

    IF v_count > 0 THEN
      EXECUTE IMMEDIATE
        'ALTER TABLE ' || p_table_name ||
        ' MODIFY ' || p_column_name ||
        ' GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)';
      DBMS_OUTPUT.PUT_LINE('OK RESET IDENTITY ' || p_table_name || '.' || p_column_name);
    ELSE
      DBMS_OUTPUT.PUT_LINE('SIN IDENTITY ' || p_table_name || '.' || p_column_name);
    END IF;
  EXCEPTION
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('NO SE PUDO RESET IDENTITY ' || p_table_name || '.' || p_column_name || ': ' || SQLERRM);
  END;
BEGIN
  IF USER <> 'SDRERC_APP' THEN
    RAISE_APPLICATION_ERROR(-20001, 'Conectate como SDRERC_APP antes de ejecutar esta limpieza.');
  END IF;

  DELETE FROM expediente_documento_analizado
   WHERE id_documento_padre IS NOT NULL;

  delete_if_exists('EXPEDIENTE_CARGO_ACUSE');
  delete_if_exists('EXPEDIENTE_PUBLICACION');
  delete_if_exists('EXPEDIENTE_NOTIFICACION');
  delete_if_exists('EXPEDIENTE_DERIVACION_EXTERNA');
  delete_if_exists('EXPEDIENTE_RESOLUCION');
  delete_if_exists('EXPEDIENTE_DIGITAL');
  delete_if_exists('EXPEDIENTE_HISTORIAL');
  delete_if_exists('EXPEDIENTE_METRICA_ETAPA');
  delete_if_exists('EXPEDIENTE_ALERTA');
  delete_if_exists('EXPEDIENTE_PLAZO');
  delete_if_exists('EXPEDIENTE_OBSERVACION');
  delete_if_exists('EXPEDIENTE_EVALUACION');
  delete_if_exists('EXPEDIENTE_DOCUMENTO_ANALIZADO');
  delete_if_exists('EXPEDIENTE_ANALISIS');
  delete_if_exists('EXPEDIENTE_DOCUMENTO');
  delete_if_exists('EXPEDIENTE_ASIGNACION');
  delete_if_exists('EXPEDIENTE_RELACION');
  delete_if_exists('EXPEDIENTE_ACTA');
  delete_if_exists('EXPEDIENTE_PERSONA');
  delete_if_exists('EXPEDIENTE_SOLICITUD');
  delete_if_exists('EXPEDIENTE');
  delete_if_exists('PERSONA');

  COMMIT;

  reset_identity_if_exists('PERSONA', 'ID_PERSONA');
  reset_identity_if_exists('EXPEDIENTE', 'ID_EXPEDIENTE');
  reset_identity_if_exists('EXPEDIENTE_SOLICITUD', 'ID_EXPEDIENTE_SOLICITUD');
  reset_identity_if_exists('EXPEDIENTE_PERSONA', 'ID_EXPEDIENTE_PERSONA');
  reset_identity_if_exists('EXPEDIENTE_ACTA', 'ID_EXPEDIENTE_ACTA');
  reset_identity_if_exists('EXPEDIENTE_RELACION', 'ID_EXPEDIENTE_RELACION');
  reset_identity_if_exists('EXPEDIENTE_ASIGNACION', 'ID_EXPEDIENTE_ASIGNACION');
  reset_identity_if_exists('EXPEDIENTE_DOCUMENTO', 'ID_EXPEDIENTE_DOCUMENTO');
  reset_identity_if_exists('EXPEDIENTE_DOCUMENTO_ANALIZADO', 'ID_DOCUMENTO_ANALIZADO');
  reset_identity_if_exists('EXPEDIENTE_ANALISIS', 'ID_EXPEDIENTE_ANALISIS');
  reset_identity_if_exists('EXPEDIENTE_EVALUACION', 'ID_EXPEDIENTE_EVALUACION');
  reset_identity_if_exists('EXPEDIENTE_OBSERVACION', 'ID_EXPEDIENTE_OBSERVACION');
  reset_identity_if_exists('EXPEDIENTE_RESOLUCION', 'ID_EXPEDIENTE_RESOLUCION');
  reset_identity_if_exists('EXPEDIENTE_NOTIFICACION', 'ID_EXPEDIENTE_NOTIFICACION');
  reset_identity_if_exists('EXPEDIENTE_CARGO_ACUSE', 'ID_EXPEDIENTE_CARGO_ACUSE');
  reset_identity_if_exists('EXPEDIENTE_DIGITAL', 'ID_EXPEDIENTE_DIGITAL');
  reset_identity_if_exists('EXPEDIENTE_HISTORIAL', 'ID_EXPEDIENTE_HISTORIAL');
  reset_identity_if_exists('EXPEDIENTE_DERIVACION_EXTERNA', 'ID_DERIVACION_EXTERNA');
  reset_identity_if_exists('EXPEDIENTE_PUBLICACION', 'ID_EXPEDIENTE_PUBLICACION');
  reset_identity_if_exists('EXPEDIENTE_PLAZO', 'ID_EXPEDIENTE_PLAZO');
  reset_identity_if_exists('EXPEDIENTE_ALERTA', 'ID_EXPEDIENTE_ALERTA');
  reset_identity_if_exists('EXPEDIENTE_METRICA_ETAPA', 'ID_EXPEDIENTE_METRICA_ETAPA');

  COMMIT;
END;


SELECT 'EXPEDIENTE' tabla, COUNT(*) total FROM expediente
UNION ALL SELECT 'EXPEDIENTE_SOLICITUD', COUNT(*) FROM expediente_solicitud
UNION ALL SELECT 'EXPEDIENTE_PERSONA', COUNT(*) FROM expediente_persona
UNION ALL SELECT 'EXPEDIENTE_ACTA', COUNT(*) FROM expediente_acta
UNION ALL SELECT 'EXPEDIENTE_DOCUMENTO_ANALIZADO', COUNT(*) FROM expediente_documento_analizado
UNION ALL SELECT 'PERSONA', COUNT(*) FROM persona;
