/* ============================================================
   SCRIPT 57 - Catalogo "Resultado de validacion" para Notificacion
   Ejecutar conectado como SDRERC_APP.

   Contexto: la Bandeja Validacion del modulo Notificacion necesita
   un combo "Resultado de validacion" con dos opciones (Aprobado /
   Observado) para que el validador decida si el documento queda
   Validado (estado_documento VALIDADO, ya existente) u Observado
   (estado_documento OBSERVADO, ya existente desde
   20_datos_maestros_flujo_to_be_v2_bpmn.sql). Este script solo crea
   el catalogo de opciones para el combo de la UI; no crea estados de
   documento nuevos ni toca expediente_documento_analizado.

   Idempotente: crea la tabla solo si no existe y siembra los codigos
   solo si no existen.
   ============================================================ */

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'TIPO_RESULTADO_VALIDACION';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE tipo_resultado_validacion (
        id_tipo_resultado_validacion NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        codigo VARCHAR2(60) NOT NULL,
        nombre VARCHAR2(150) NOT NULL,
        activo NUMBER(1) DEFAULT 1 NOT NULL,
        creado_por NUMBER,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        modificado_por NUMBER,
        modificado_en TIMESTAMP
      )
    ]';
    EXECUTE IMMEDIATE q'[
      ALTER TABLE tipo_resultado_validacion
      ADD CONSTRAINT pk_tipo_resultado_validacion PRIMARY KEY (id_tipo_resultado_validacion)
    ]';
    EXECUTE IMMEDIATE q'[
      ALTER TABLE tipo_resultado_validacion
      ADD CONSTRAINT uk_tipo_resultado_validacion_cod UNIQUE (codigo)
    ]';
  END IF;
END;
/

MERGE INTO tipo_resultado_validacion dst
USING (
  SELECT 'APROBADO' AS codigo, 'Aprobado' AS nombre FROM dual
  UNION ALL SELECT 'OBSERVADO', 'Observado' FROM dual
) src
ON (UPPER(dst.codigo) = src.codigo)
WHEN MATCHED THEN UPDATE
  SET dst.nombre = src.nombre,
      dst.activo = 1,
      dst.modificado_en = SYSTIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (codigo, nombre, activo)
  VALUES (src.codigo, src.nombre, 1);

COMMIT;

/* ============================================================
   Verificacion posterior
   ============================================================ */

SELECT codigo, nombre, activo FROM tipo_resultado_validacion ORDER BY id_tipo_resultado_validacion;
