/* ============================================================
   SCRIPT 61 - Soporte de esquema para Login premium con 2FA (TOTP)
   Ejecutar conectado como SDRERC_APP.

   Contexto: hoy la columna usuario.password_hash existe pero nunca se
   usa (UsuarioDAO.insertarUsuario la fija a NULL, actualizarUsuario ni
   siquiera la actualiza) y MainV2 abre MenuPrincipalV2 sin ningun
   login. Este script agrega el soporte de esquema necesario para:

   - Forzar cambio de contraseña en el primer login tras un
     "Restablecer clave" del administrador (debe_cambiar_password).
   - Enrolamiento y verificacion TOTP (RFC 6238) por usuario
     (totp_secret cifrado en la capa de aplicacion con AES-GCM, nunca
     en claro; totp_habilitado; totp_confirmado_en).
   - Bloqueo temporal tras intentos fallidos de password o de codigo
     TOTP (intentos_fallidos, bloqueado_hasta).
   - Auditoria minima (password_actualizado_en, ultimo_login_en).
   - Codigos de respaldo de un solo uso para cuando se pierde el
     dispositivo autenticador (tabla usuario_totp_backup_code, mismo
     patron de hash que password_hash: BCrypt via PasswordEncoder).

   No se toca ninguna tabla ni columna legacy (APP_USERS, etc.). No
   se toca OracleConnection.java ni el flujo de login legacy.

   Idempotente en su totalidad (verifica user_tab_columns/user_tables
   antes de cada ALTER/CREATE).
   ============================================================ */

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_tab_columns
   WHERE table_name = 'USUARIO' AND column_name = 'DEBE_CAMBIAR_PASSWORD';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE usuario ADD (debe_cambiar_password NUMBER(1) DEFAULT 0 NOT NULL)';
  END IF;
END;


DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_tab_columns
   WHERE table_name = 'USUARIO' AND column_name = 'TOTP_SECRET';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE usuario ADD (totp_secret VARCHAR2(255))';
  END IF;
END;


DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_tab_columns
   WHERE table_name = 'USUARIO' AND column_name = 'TOTP_HABILITADO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE usuario ADD (totp_habilitado NUMBER(1) DEFAULT 0 NOT NULL)';
  END IF;
END;


DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_tab_columns
   WHERE table_name = 'USUARIO' AND column_name = 'TOTP_CONFIRMADO_EN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE usuario ADD (totp_confirmado_en TIMESTAMP)';
  END IF;
END;


DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_tab_columns
   WHERE table_name = 'USUARIO' AND column_name = 'INTENTOS_FALLIDOS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE usuario ADD (intentos_fallidos NUMBER(3) DEFAULT 0 NOT NULL)';
  END IF;
END;


DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_tab_columns
   WHERE table_name = 'USUARIO' AND column_name = 'BLOQUEADO_HASTA';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE usuario ADD (bloqueado_hasta TIMESTAMP)';
  END IF;
END;


DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_tab_columns
   WHERE table_name = 'USUARIO' AND column_name = 'PASSWORD_ACTUALIZADO_EN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE usuario ADD (password_actualizado_en TIMESTAMP)';
  END IF;
END;


DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_tab_columns
   WHERE table_name = 'USUARIO' AND column_name = 'ULTIMO_LOGIN_EN';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE usuario ADD (ultimo_login_en TIMESTAMP)';
  END IF;
END;


DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_tables
   WHERE table_name = 'USUARIO_TOTP_BACKUP_CODE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE usuario_totp_backup_code (
        id_backup_code NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_usuario NUMBER NOT NULL,
        codigo_hash VARCHAR2(250) NOT NULL,
        usado NUMBER(1) DEFAULT 0 NOT NULL,
        usado_en TIMESTAMP,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;


DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_constraints
   WHERE table_name = 'USUARIO_TOTP_BACKUP_CODE'
     AND constraint_name = 'FK_USR_TOTP_BACKUP_USUARIO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE usuario_totp_backup_code
      ADD CONSTRAINT fk_usr_totp_backup_usuario
      FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario)
    ]';
  END IF;
END;


/* ============================================================
   Verificacion posterior
   ============================================================ */

SELECT column_name FROM user_tab_columns
 WHERE table_name = 'USUARIO'
   AND column_name IN ('DEBE_CAMBIAR_PASSWORD', 'TOTP_SECRET', 'TOTP_HABILITADO',
                        'TOTP_CONFIRMADO_EN', 'INTENTOS_FALLIDOS', 'BLOQUEADO_HASTA',
                        'PASSWORD_ACTUALIZADO_EN', 'ULTIMO_LOGIN_EN')
 ORDER BY column_name;

SELECT table_name FROM user_tables WHERE table_name = 'USUARIO_TOTP_BACKUP_CODE';


/* ============================================================
   BOOTSTRAP MANUAL - NO AUTOMATICO - EJECUTAR SOLO UNA VEZ,
   BAJO AUTORIZACION EXPLICITA, DESPUES DE LO ANTERIOR.

   Hoy ningun usuario tiene password_hash. Como la asignacion de
   clave es responsabilidad del administrador desde una pantalla que
   requiere login (Administracion > Usuarios > "Restablecer clave"),
   hace falta destrabar el primer acceso de un ADMIN_SISTEMA a mano:

   1) Ejecutar localmente la clase utilitaria
      com.sdrerc.tools.PasswordHashCli con una contraseña temporal
      elegida por ti (no se guarda en ningun archivo del repo), para
      obtener su hash BCrypt.
   2) Reemplazar :HASH_BCRYPT_TEMPORAL abajo por ese hash.
   3) Reemplazar :USERNAME_ADMIN_BOOTSTRAP por el username exacto del
      usuario ADMIN_SISTEMA que vas a usar para el primer ingreso.
   4) Ejecutar solo el UPDATE de abajo (no repetirlo despues del
      primer login exitoso).

   UPDATE usuario
      SET password_hash = ':HASH_BCRYPT_TEMPORAL',
          debe_cambiar_password = 1,
          totp_habilitado = 0,
          intentos_fallidos = 0,
          bloqueado_hasta = NULL,
          password_actualizado_en = SYSTIMESTAMP
    WHERE UPPER(username) = UPPER(':USERNAME_ADMIN_BOOTSTRAP')
      AND activo = 1
      AND UPPER(estado) = 'ACTIVO';

   COMMIT;
   ============================================================ */
