/* ============================================================
   SCRIPT 75 - Administrador de plantillas de documento (Fase 2)
   Ejecutar conectado como SDRERC_APP.

   Contexto: hoy las plantillas Word que usa el icono "Word" de Analisis
   (y reutiliza Ejecucion) son archivos sueltos en docs/plantillas,
   resueltos por coincidencia aproximada de nombre de archivo
   (AnalisisPlantillaDocumentoService.resolverPlantilla). No hay forma de
   versionarlas ni de administrarlas sin tocar el file share y sin
   recompilar. Pedido explicito del usuario ("Fase 2"): un modulo
   Administracion > Plantillas de documento donde se pueda cargar una
   nueva version de la plantilla por tipo de documento, ver el
   historial de versiones y reactivar una version anterior.

   Que hace:
   1) Crea la tabla PLANTILLA_DOCUMENTO: guarda el contenido del .docx
      como BLOB (no como archivo en disco), versionado por
      id_tipo_documento_adjunto. Se eligio BLOB en Oracle -no archivo en
      el file share- porque el modelo de despliegue vigente es que cada
      cliente COPIA la app localmente (C:\SDRERC_CLIENTE\app); un archivo
      nuevo dejado solo en el disco de quien lo sube no se veria en las
      demas maquinas hasta el proximo release. Oracle es el unico
      recurso realmente compartido y accesible en vivo por todos los
      clientes de la LAN.
   2) Solo una version puede estar activa (activo=1) por tipo de
      documento; esa regla se aplica en Java (PlantillaDocumentoDAO), no
      con un trigger.
   3) Si NO existe ninguna fila activa para un tipo de documento, el
      sistema sigue resolviendo la plantilla como hasta ahora (archivo en
      docs/plantillas por coincidencia de nombre): esta tabla es un
      mecanismo de adopcion gradual, no una migracion forzada de las
      plantillas existentes.
   4) Siembra el permiso de menu MENU_ADMIN_PLANTILLAS (modulo
      Administracion) y lo otorga integro a ADMIN_SISTEMA, mismo patron
      que 59_catalogo_permisos_menu.sql.

   Idempotente: CREATE TABLE protegido por chequeo de existencia: el
   MERGE de permisos se puede reejecutar sin duplicar.
   ============================================================ */

DECLARE
  v_existe NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_existe FROM user_tables WHERE table_name = 'PLANTILLA_DOCUMENTO';
  IF v_existe = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE plantilla_documento (
        id_plantilla_documento NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_tipo_documento_adjunto NUMBER NOT NULL,
        version NUMBER NOT NULL,
        nombre_archivo VARCHAR2(200) NOT NULL,
        contenido BLOB NOT NULL,
        tamano_bytes NUMBER,
        comentario VARCHAR2(500),
        activo NUMBER(1) DEFAULT 1 NOT NULL,
        creado_por NUMBER,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        modificado_por NUMBER,
        modificado_en TIMESTAMP,
        CONSTRAINT pk_plantilla_documento PRIMARY KEY (id_plantilla_documento),
        CONSTRAINT fk_plantilla_doc_tipo FOREIGN KEY (id_tipo_documento_adjunto)
          REFERENCES tipo_documento_adjunto(id_tipo_documento_adjunto),
        CONSTRAINT uq_plantilla_doc_version UNIQUE (id_tipo_documento_adjunto, version)
      )';
    EXECUTE IMMEDIATE 'CREATE INDEX ix_plantilla_doc_tipo_activo ON plantilla_documento(id_tipo_documento_adjunto, activo)';
  END IF;
END;


/* ------------------------------------------------------------
   Permiso de menu MENU_ADMIN_PLANTILLAS, otorgado a ADMIN_SISTEMA
   ------------------------------------------------------------ */

MERGE INTO permiso dst
USING (
  SELECT 'MENU_ADMIN_PLANTILLAS' AS codigo, 'Administrar Plantillas de documento' AS nombre, 'Administracion' AS modulo FROM dual
) src
ON (UPPER(dst.codigo) = src.codigo)
WHEN MATCHED THEN UPDATE
  SET dst.nombre = src.nombre,
      dst.modulo = src.modulo,
      dst.activo = 1,
      dst.modificado_en = SYSTIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (codigo, nombre, modulo, activo)
  VALUES (src.codigo, src.nombre, src.modulo, 1);

COMMIT;

MERGE INTO rol_permiso dst
USING (
  SELECT r.id_rol AS id_rol, p.id_permiso AS id_permiso
  FROM rol r
  CROSS JOIN permiso p
  WHERE UPPER(r.codigo) = 'ADMIN_SISTEMA'
    AND r.activo = 1
    AND p.activo = 1
    AND p.codigo = 'MENU_ADMIN_PLANTILLAS'
) src
ON (dst.id_rol = src.id_rol AND dst.id_permiso = src.id_permiso)
WHEN MATCHED THEN UPDATE
  SET dst.activo = 1,
      dst.modificado_en = SYSTIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (id_rol, id_permiso, activo)
  VALUES (src.id_rol, src.id_permiso, 1);

COMMIT;

/* ============================================================
   Verificacion posterior
   ============================================================ */

SELECT table_name FROM user_tables WHERE table_name = 'PLANTILLA_DOCUMENTO';

SELECT codigo, nombre, modulo, activo FROM permiso WHERE codigo = 'MENU_ADMIN_PLANTILLAS';
