/* ============================================================
   SCRIPT 76 - Bloques de contenido para plantillas de documento
   Ejecutar conectado como SDRERC_APP.

   Contexto: pedido explicito del usuario, evolucion del administrador
   de plantillas (75_plantilla_documento.sql). En vez de escribir texto
   crudo con marcadores [[SI_variable:valor]] dentro del propio Word, el
   administrador arma el contenido dinamico de una plantilla como una
   lista ordenada de "bloques" (titulo + contenido + condicion opcional)
   desde un formulario en la app. Al generar el documento, los bloques
   cuya condicion se cumple se insertan, en orden, en el punto de la
   plantilla base marcado con el parrafo literal [[CONTENIDO]].

   Que hace:
   1) Crea la tabla PLANTILLA_BLOQUE: un bloque por fila, versionado por
      id_tipo_documento_adjunto (independiente de la plantilla base /
      PLANTILLA_DOCUMENTO, para que cambiar el membrete/logo de la base
      no afecte los bloques de contenido ya configurados).
   2) La condicion de un bloque (variable_condicion/operador_condicion/
      valores_condicion) es opcional: si variable_condicion es NULL, el
      bloque siempre se incluye. Si tiene valor, se evalua contra el
      mismo mapa de variables que ya resuelve los #variable# (reusa
      AnalisisPlantillaDocumentoService.coincideCriterio), con
      operador_condicion en ('COINCIDE', 'NO_COINCIDE') y
      valores_condicion como lista separada por "|" (mismo formato que
      los marcadores [[SI_...]] existentes).

   No migra ni toca ningun .docx existente. No crea bloques de ejemplo.

   Idempotente: CREATE TABLE protegido por chequeo de existencia.
   ============================================================ */

DECLARE
  v_existe NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_existe FROM user_tables WHERE table_name = 'PLANTILLA_BLOQUE';
  IF v_existe = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE plantilla_bloque (
        id_plantilla_bloque NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_tipo_documento_adjunto NUMBER NOT NULL,
        orden NUMBER NOT NULL,
        titulo VARCHAR2(200),
        contenido CLOB NOT NULL,
        variable_condicion VARCHAR2(80),
        operador_condicion VARCHAR2(20),
        valores_condicion VARCHAR2(500),
        activo NUMBER(1) DEFAULT 1 NOT NULL,
        creado_por NUMBER,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        modificado_por NUMBER,
        modificado_en TIMESTAMP,
        CONSTRAINT pk_plantilla_bloque PRIMARY KEY (id_plantilla_bloque),
        CONSTRAINT fk_plantilla_bloque_tipo FOREIGN KEY (id_tipo_documento_adjunto)
          REFERENCES tipo_documento_adjunto(id_tipo_documento_adjunto),
        CONSTRAINT ck_plantilla_bloque_operador CHECK (operador_condicion IS NULL
          OR operador_condicion IN (''COINCIDE'', ''NO_COINCIDE''))
      )';
    EXECUTE IMMEDIATE 'CREATE INDEX ix_plantilla_bloque_tipo ON plantilla_bloque(id_tipo_documento_adjunto, activo, orden)';
  END IF;
END;


/* ============================================================
   Verificacion posterior
   ============================================================ */

SELECT table_name FROM user_tables WHERE table_name = 'PLANTILLA_BLOQUE';
