-- Fase 2 de Grupo Familiar (evoluciona la Fase 1 de 27_grupo_familiar_fase1.sql, que solo
-- agrego una marca booleana en EXPEDIENTE_SOLICITUD sin vincular integrantes entre si).
--
-- Agrega una tabla ancla GRUPO_FAMILIAR (solo un ID que agrupa) y una columna
-- PERSONA.id_grupo_familiar. El vinculo se hace a nivel PERSONA, no por expediente: si el
-- mismo titular (misma fila de PERSONA) vuelve a aparecer como titular en un expediente
-- futuro, hereda el grupo familiar automaticamente sin necesidad de volver a asociarlo.
--
-- No se reutiliza EXPEDIENTE_RELACION (evita mezclar grupo familiar con la logica de
-- duplicidad, que hereda numero de expediente/equipo/abogado; grupo familiar no debe
-- heredar nada de eso).
--
-- Idempotente: puede reejecutarse sin duplicar tabla, columna, FK, indice ni tipo de
-- movimiento.

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count FROM user_tables WHERE table_name = 'GRUPO_FAMILIAR';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE grupo_familiar (
        id_grupo_familiar NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        activo NUMBER(1) DEFAULT 1 NOT NULL,
        creado_por NUMBER,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        modificado_por NUMBER,
        modificado_en TIMESTAMP,
        CONSTRAINT pk_grupo_familiar PRIMARY KEY (id_grupo_familiar)
      )
    ]';
    EXECUTE IMMEDIATE q'[
      COMMENT ON TABLE grupo_familiar IS
      'Ancla de grupo familiar: agrupa PERSONA.id_grupo_familiar. Sin datos propios ademas del ID.'
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_tab_columns
   WHERE table_name = 'PERSONA' AND column_name = 'ID_GRUPO_FAMILIAR';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE persona ADD id_grupo_familiar NUMBER';
    EXECUTE IMMEDIATE q'[
      COMMENT ON COLUMN persona.id_grupo_familiar IS
      'Grupo familiar al que pertenece esta persona (nullable). Vinculo a nivel persona: se
      hereda automaticamente si la misma persona vuelve a ser titular de otro expediente.'
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_constraints
   WHERE table_name = 'PERSONA' AND constraint_name = 'FK_PERSONA_GRUPO_FAMILIAR';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE persona
      ADD CONSTRAINT fk_persona_grupo_familiar
      FOREIGN KEY (id_grupo_familiar) REFERENCES grupo_familiar (id_grupo_familiar)
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_indexes
   WHERE table_name = 'PERSONA' AND index_name = 'IX_PERSONA_GRUPO_FAMILIAR';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_persona_grupo_familiar ON persona(id_grupo_familiar)';
  END IF;
END;
/

INSERT INTO tipo_movimiento (codigo, nombre)
SELECT 'ASOCIACION_GRUPO_FAMILIAR', 'Asociacion de grupo familiar'
FROM dual
WHERE NOT EXISTS (
  SELECT 1 FROM tipo_movimiento WHERE codigo = 'ASOCIACION_GRUPO_FAMILIAR'
);

COMMIT;

SELECT table_name FROM user_tables WHERE table_name = 'GRUPO_FAMILIAR';
SELECT column_name, data_type, nullable FROM user_tab_columns
 WHERE table_name = 'PERSONA' AND column_name = 'ID_GRUPO_FAMILIAR';
SELECT codigo, nombre, activo FROM tipo_movimiento WHERE codigo = 'ASOCIACION_GRUPO_FAMILIAR';
