/* ============================================================
   SCRIPT 82 - Soporte de esquema para 2FA por correo electronico (login V2)
   Ejecutar conectado como SDRERC_APP.

   Contexto: se agrega el correo electronico como PRIMERA opcion de doble
   factor en el login (LoginFrameV2), dejando el authenticator TOTP (RFC 6238,
   script 61) como segunda opcion alternativa, no reemplazada. A diferencia de
   TOTP, el correo no requiere una ceremonia de "enrolamiento" (QR, secreto,
   confirmacion): si el usuario ya tiene usuario.correo cargado, ese es el
   metodo ofrecido primero; si no lo tiene, el flujo cae automaticamente a
   TOTP exactamente como hasta ahora.

   Esta tabla guarda el codigo OTP de un solo uso enviado por correo en cada
   login, con el mismo patron que usuario_totp_backup_code (script 61):
   hash BCrypt (nunca en claro), de un solo uso, con expiracion.

   No se toca ninguna tabla ni columna legacy. No se toca OracleConnection.java
   ni el flujo de login legacy.

   Idempotente en su totalidad (verifica user_tables antes de CREATE).
   ============================================================ */

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_tables
   WHERE table_name = 'USUARIO_EMAIL_OTP';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE usuario_email_otp (
        id_email_otp NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        id_usuario NUMBER NOT NULL,
        codigo_hash VARCHAR2(250) NOT NULL,
        expira_en TIMESTAMP NOT NULL,
        usado NUMBER(1) DEFAULT 0 NOT NULL,
        usado_en TIMESTAMP,
        creado_en TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/


DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(1) INTO v_count
    FROM user_constraints
   WHERE table_name = 'USUARIO_EMAIL_OTP'
     AND constraint_name = 'FK_USR_EMAIL_OTP_USUARIO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE usuario_email_otp
      ADD CONSTRAINT fk_usr_email_otp_usuario
      FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario)
    ]';
  END IF;
END;
/


/* ============================================================
   Verificacion posterior
   ============================================================ */

SELECT table_name FROM user_tables WHERE table_name = 'USUARIO_EMAIL_OTP';

SELECT column_name, data_type, nullable FROM user_tab_columns
 WHERE table_name = 'USUARIO_EMAIL_OTP'
 ORDER BY column_id;
