DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'EXPEDIENTE'
       AND COLUMN_NAME = 'DNI_TITULAR_2';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EXPEDIENTE ADD DNI_TITULAR_2 CHAR(8)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'EXPEDIENTE'
       AND COLUMN_NAME = 'APELLIDO_NOMBRE_TITULAR_2';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE EXPEDIENTE ADD APELLIDO_NOMBRE_TITULAR_2 VARCHAR2(500)';
    END IF;
END;
/

COMMENT ON COLUMN EXPEDIENTE.DNI_TITULAR_2 IS 'DNI del segundo titular para actas de matrimonio';
COMMENT ON COLUMN EXPEDIENTE.APELLIDO_NOMBRE_TITULAR_2 IS 'Apellidos y nombres del segundo titular para actas de matrimonio';
