ALTER TABLE EXPEDIENTE DROP COLUMN FECHA_RECEPCION;

ALTER TABLE EXPEDIENTE ADD CANAL_RECEPCION VARCHAR2(30 CHAR);

COMMENT ON COLUMN EXPEDIENTE.CANAL_RECEPCION IS 'Canal de recepcion del expediente';

UPDATE EXPEDIENTE
SET CANAL_RECEPCION = 'INTERNO'
WHERE CANAL_RECEPCION IS NULL;

ALTER TABLE EXPEDIENTE MODIFY CANAL_RECEPCION NOT NULL;
